$(function() {
    var instructor = new PITT.Pitt(true)
    var gui = new GUI.GUI()
    gui.init()
    instructor.onUpdateState(gui.onStateChange)
    instructor.onUpdateUserId(gui.onUpdateUserId)
    instructor.onUpdateStudents(gui.onUpdateStudents)
    instructor.onUpdateInstructors(gui.onUpdateInstructors)
    instructor.onIncomingCall(gui.onIncomingCall)
    instructor.onUpdateCountdown(gui.onUpdateCountdown)
    instructor.onNewChatMessage(gui.onNewChatMessage)

    instructor.init(gui.media_access, gui.media_error)
    gui.onStartBroadcasting(instructor.start_broadcast)
    gui.onStopBroadcasting(instructor.stop_broadcast)
    gui.onSplitStudents(instructor.start_split_mode)
    gui.onBackToBroadcast(instructor.countdown, instructor.stop_split_mode)
    gui.onSendMessage(instructor.send_message)
})
